"""Opportunity universe, scores, and modeling assumptions.

Scoring convention (1–10):
  Positive criteria: higher is better.
  Burden/risk criteria: higher is worse (more capital, more time, more risk).
"""

from __future__ import annotations

USD_BDT = 122.0  # Working mid-market assumption ~Aug 2026; label as estimate.

POSITIVE = {
    "income_potential",
    "scalability",
    "passivity",
    "skill_fit",
    "bd_feasibility",
    "intl_feasibility",
    "sustainability",
    "automation",
    "exit_potential",
}

BURDEN = {
    "capital",
    "setup_time",
    "weekly_time",
    "time_to_income",
    "tech_difficulty",
    "competition",
    "reg_complexity",
    "tax_complexity",
    "employer_conflict",
    "independence_risk",
    "confidentiality_risk",
    "reputation_risk",
    "financial_risk",
    "failure_prob",
    "ai_disruption",
}

CRITERIA_LABELS = {
    "capital": "Initial capital (higher = more capital)",
    "setup_time": "Initial setup time (higher = longer)",
    "weekly_time": "Weekly maintenance (higher = more hours)",
    "time_to_income": "Time to first income (higher = slower)",
    "income_potential": "Expected income potential",
    "scalability": "Scalability",
    "passivity": "Degree of passivity",
    "tech_difficulty": "Technical difficulty (higher = harder)",
    "skill_fit": "Skill fit to audit/finance profile",
    "competition": "Competition intensity (higher = tougher)",
    "bd_feasibility": "Bangladesh feasibility",
    "intl_feasibility": "International feasibility",
    "reg_complexity": "Regulatory complexity (higher = harder)",
    "tax_complexity": "Tax complexity (higher = harder)",
    "employer_conflict": "Employer-conflict risk",
    "independence_risk": "Professional-independence risk",
    "confidentiality_risk": "Confidentiality risk",
    "reputation_risk": "Reputation risk",
    "financial_risk": "Financial risk",
    "failure_prob": "Probability of failure",
    "sustainability": "Long-term sustainability",
    "ai_disruption": "AI disruption risk",
    "automation": "Automation potential",
    "exit_potential": "Exit / sale potential",
}

# Weights for composite 0–100 score. Positive add; burden subtracts after inversion.
WEIGHTS = {
    "income_potential": 0.10,
    "scalability": 0.09,
    "passivity": 0.09,
    "skill_fit": 0.08,
    "bd_feasibility": 0.06,
    "intl_feasibility": 0.04,
    "sustainability": 0.06,
    "automation": 0.04,
    "exit_potential": 0.03,
    "capital": 0.04,
    "setup_time": 0.03,
    "weekly_time": 0.05,
    "time_to_income": 0.03,
    "tech_difficulty": 0.02,
    "competition": 0.03,
    "reg_complexity": 0.03,
    "tax_complexity": 0.02,
    "employer_conflict": 0.08,
    "independence_risk": 0.08,
    "confidentiality_risk": 0.05,
    "reputation_risk": 0.05,
    "financial_risk": 0.03,
    "failure_prob": 0.03,
    "ai_disruption": 0.02,
}

# category: A truly passive / B semi-passive / C leveraged active
# permission: 1 permitted-personal  2 usually ok if generic  3 approval likely
#             4 high conflict  5 avoid

OPPS = [
    dict(
        id=1, name="Bank fixed deposit (FDR)", cat="A", family="Investment",
        permission=1, permission_label="Generally permissible personal investment",
        capital=4, setup_time=1, weekly_time=1, time_to_income=2, income_potential=3,
        scalability=2, passivity=10, tech_difficulty=1, skill_fit=8, competition=2,
        bd_feasibility=10, intl_feasibility=1, reg_complexity=2, tax_complexity=3,
        employer_conflict=1, independence_risk=2, confidentiality_risk=1, reputation_risk=1,
        financial_risk=2, failure_prob=1, sustainability=7, ai_disruption=1,
        automation=8, exit_potential=3,
    ),
    dict(
        id=2, name="National Savings Certificates (Sanchayapatra)", cat="A", family="Investment",
        permission=1, permission_label="Generally permissible sovereign product",
        capital=5, setup_time=2, weekly_time=1, time_to_income=2, income_potential=4,
        scalability=2, passivity=10, tech_difficulty=1, skill_fit=8, competition=2,
        bd_feasibility=10, intl_feasibility=1, reg_complexity=3, tax_complexity=4,
        employer_conflict=1, independence_risk=1, confidentiality_risk=1, reputation_risk=1,
        financial_risk=2, failure_prob=1, sustainability=7, ai_disruption=1,
        automation=6, exit_potential=3,
    ),
    dict(
        id=3, name="Treasury bills (91/182/364-day)", cat="A", family="Investment",
        permission=1, permission_label="Generally permissible sovereign security",
        capital=5, setup_time=3, weekly_time=1, time_to_income=2, income_potential=4,
        scalability=4, passivity=9, tech_difficulty=3, skill_fit=9, competition=2,
        bd_feasibility=9, intl_feasibility=1, reg_complexity=3, tax_complexity=4,
        employer_conflict=1, independence_risk=1, confidentiality_risk=1, reputation_risk=1,
        financial_risk=2, failure_prob=2, sustainability=8, ai_disruption=1,
        automation=7, exit_potential=5,
    ),
    dict(
        id=4, name="Bangladesh Government Treasury Bonds", cat="A", family="Investment",
        permission=1, permission_label="Generally permissible sovereign security",
        capital=5, setup_time=3, weekly_time=1, time_to_income=3, income_potential=5,
        scalability=5, passivity=9, tech_difficulty=3, skill_fit=9, competition=2,
        bd_feasibility=9, intl_feasibility=1, reg_complexity=3, tax_complexity=4,
        employer_conflict=1, independence_risk=1, confidentiality_risk=1, reputation_risk=1,
        financial_risk=3, failure_prob=2, sustainability=9, ai_disruption=1,
        automation=7, exit_potential=6,
    ),
    dict(
        id=5, name="Bank DPS / recurring deposit", cat="A", family="Investment",
        permission=1, permission_label="Generally permissible personal savings",
        capital=2, setup_time=1, weekly_time=1, time_to_income=4, income_potential=3,
        scalability=3, passivity=10, tech_difficulty=1, skill_fit=7, competition=2,
        bd_feasibility=10, intl_feasibility=1, reg_complexity=2, tax_complexity=3,
        employer_conflict=1, independence_risk=1, confidentiality_risk=1, reputation_risk=1,
        financial_risk=2, failure_prob=1, sustainability=7, ai_disruption=1,
        automation=8, exit_potential=2,
    ),
    dict(
        id=6, name="Islamic term deposit / Mudaraba", cat="A", family="Investment",
        permission=1, permission_label="Generally permissible personal deposit",
        capital=4, setup_time=2, weekly_time=1, time_to_income=2, income_potential=3,
        scalability=2, passivity=10, tech_difficulty=1, skill_fit=7, competition=2,
        bd_feasibility=10, intl_feasibility=1, reg_complexity=2, tax_complexity=3,
        employer_conflict=1, independence_risk=2, confidentiality_risk=1, reputation_risk=1,
        financial_risk=2, failure_prob=1, sustainability=7, ai_disruption=1,
        automation=7, exit_potential=3,
    ),
    dict(
        id=7, name="Open-end mutual funds (income/balanced)", cat="A", family="Investment",
        permission=2, permission_label="Permissible if holdings screened vs restricted list",
        capital=3, setup_time=3, weekly_time=2, time_to_income=3, income_potential=5,
        scalability=6, passivity=8, tech_difficulty=3, skill_fit=9, competition=4,
        bd_feasibility=8, intl_feasibility=2, reg_complexity=4, tax_complexity=4,
        employer_conflict=3, independence_risk=6, confidentiality_risk=1, reputation_risk=3,
        financial_risk=5, failure_prob=4, sustainability=7, ai_disruption=2,
        automation=7, exit_potential=6,
    ),
    dict(
        id=8, name="Diversified DSE blue-chip portfolio", cat="A", family="Investment",
        permission=3, permission_label="Pre-clear / report; avoid restricted entities",
        capital=5, setup_time=4, weekly_time=3, time_to_income=4, income_potential=6,
        scalability=6, passivity=7, tech_difficulty=4, skill_fit=9, competition=6,
        bd_feasibility=8, intl_feasibility=2, reg_complexity=5, tax_complexity=5,
        employer_conflict=5, independence_risk=8, confidentiality_risk=4, reputation_risk=5,
        financial_risk=8, failure_prob=6, sustainability=6, ai_disruption=3,
        automation=5, exit_potential=7,
    ),
    dict(
        id=9, name="Dividend-focused listed equities", cat="A", family="Investment",
        permission=3, permission_label="Pre-clear / report; avoid restricted entities",
        capital=5, setup_time=4, weekly_time=3, time_to_income=4, income_potential=5,
        scalability=5, passivity=7, tech_difficulty=4, skill_fit=9, competition=5,
        bd_feasibility=8, intl_feasibility=2, reg_complexity=5, tax_complexity=5,
        employer_conflict=5, independence_risk=8, confidentiality_risk=4, reputation_risk=5,
        financial_risk=7, failure_prob=5, sustainability=6, ai_disruption=3,
        automation=5, exit_potential=6,
    ),
    dict(
        id=10, name="Listed corporate bonds / sukuk", cat="A", family="Investment",
        permission=3, permission_label="Screen issuer vs restricted-entity list",
        capital=6, setup_time=4, weekly_time=2, time_to_income=3, income_potential=5,
        scalability=4, passivity=8, tech_difficulty=4, skill_fit=9, competition=3,
        bd_feasibility=6, intl_feasibility=2, reg_complexity=5, tax_complexity=5,
        employer_conflict=4, independence_risk=7, confidentiality_risk=2, reputation_risk=3,
        financial_risk=6, failure_prob=5, sustainability=6, ai_disruption=2,
        automation=5, exit_potential=5,
    ),
    dict(
        id=11, name="Life endowment / deferred annuity", cat="A", family="Investment",
        permission=2, permission_label="Usually personal; check insurer restricted status",
        capital=4, setup_time=3, weekly_time=1, time_to_income=8, income_potential=3,
        scalability=3, passivity=9, tech_difficulty=2, skill_fit=7, competition=3,
        bd_feasibility=8, intl_feasibility=1, reg_complexity=3, tax_complexity=4,
        employer_conflict=2, independence_risk=3, confidentiality_risk=1, reputation_risk=1,
        financial_risk=4, failure_prob=3, sustainability=6, ai_disruption=2,
        automation=6, exit_potential=3,
    ),
    dict(
        id=12, name="Pension / provident top-up products", cat="A", family="Investment",
        permission=1, permission_label="Generally personal retirement saving",
        capital=3, setup_time=2, weekly_time=1, time_to_income=9, income_potential=3,
        scalability=3, passivity=10, tech_difficulty=2, skill_fit=8, competition=2,
        bd_feasibility=8, intl_feasibility=1, reg_complexity=3, tax_complexity=4,
        employer_conflict=1, independence_risk=2, confidentiality_risk=1, reputation_risk=1,
        financial_risk=3, failure_prob=2, sustainability=8, ai_disruption=1,
        automation=7, exit_potential=2,
    ),
    dict(
        id=13, name="Physical gold / jewellery store-of-value", cat="A", family="Investment",
        permission=1, permission_label="Personal asset; not an income engine",
        capital=6, setup_time=2, weekly_time=1, time_to_income=9, income_potential=2,
        scalability=2, passivity=8, tech_difficulty=1, skill_fit=4, competition=3,
        bd_feasibility=9, intl_feasibility=4, reg_complexity=3, tax_complexity=4,
        employer_conflict=1, independence_risk=1, confidentiality_risk=1, reputation_risk=1,
        financial_risk=6, failure_prob=4, sustainability=5, ai_disruption=1,
        automation=2, exit_potential=5,
    ),
    dict(
        id=14, name="RFCD / eligible FCY deposit", cat="A", family="Investment",
        permission=2, permission_label="Only if legally eligible (e.g., ERQ/RFCD rules)",
        capital=5, setup_time=4, weekly_time=1, time_to_income=3, income_potential=3,
        scalability=3, passivity=9, tech_difficulty=3, skill_fit=7, competition=2,
        bd_feasibility=6, intl_feasibility=5, reg_complexity=7, tax_complexity=5,
        employer_conflict=2, independence_risk=2, confidentiality_risk=1, reputation_risk=2,
        financial_risk=4, failure_prob=4, sustainability=6, ai_disruption=1,
        automation=6, exit_potential=3,
    ),
    dict(
        id=15, name="REIT units (when listed/available)", cat="A", family="Investment",
        permission=3, permission_label="Screen sponsor/assets; market still nascent",
        capital=4, setup_time=4, weekly_time=2, time_to_income=5, income_potential=5,
        scalability=5, passivity=8, tech_difficulty=4, skill_fit=8, competition=3,
        bd_feasibility=4, intl_feasibility=2, reg_complexity=6, tax_complexity=5,
        employer_conflict=4, independence_risk=6, confidentiality_risk=2, reputation_risk=3,
        financial_risk=6, failure_prob=6, sustainability=6, ai_disruption=2,
        automation=6, exit_potential=6,
    ),
    dict(
        id=16, name="Original Excel finance template studio", cat="B", family="Digital product",
        permission=2, permission_label="Generic original IP; no firm/client material",
        capital=2, setup_time=6, weekly_time=4, time_to_income=5, income_potential=7,
        scalability=8, passivity=7, tech_difficulty=5, skill_fit=10, competition=7,
        bd_feasibility=8, intl_feasibility=8, reg_complexity=3, tax_complexity=4,
        employer_conflict=3, independence_risk=3, confidentiality_risk=3, reputation_risk=3,
        financial_risk=2, failure_prob=5, sustainability=8, ai_disruption=6,
        automation=8, exit_potential=7,
    ),
    dict(
        id=17, name="Power BI / dashboard template packs", cat="B", family="Digital product",
        permission=2, permission_label="Generic original IP; no client data",
        capital=2, setup_time=6, weekly_time=4, time_to_income=5, income_potential=6,
        scalability=8, passivity=7, tech_difficulty=6, skill_fit=9, competition=6,
        bd_feasibility=7, intl_feasibility=8, reg_complexity=3, tax_complexity=4,
        employer_conflict=3, independence_risk=3, confidentiality_risk=3, reputation_risk=3,
        financial_risk=2, failure_prob=5, sustainability=8, ai_disruption=6,
        automation=8, exit_potential=7,
    ),
    dict(
        id=18, name="BD SME cash-flow & VAT workbooks", cat="B", family="Digital product",
        permission=2, permission_label="Information tools, not formal tax advice",
        capital=2, setup_time=6, weekly_time=4, time_to_income=5, income_potential=7,
        scalability=7, passivity=7, tech_difficulty=5, skill_fit=10, competition=5,
        bd_feasibility=9, intl_feasibility=3, reg_complexity=5, tax_complexity=6,
        employer_conflict=4, independence_risk=4, confidentiality_risk=3, reputation_risk=4,
        financial_risk=2, failure_prob=5, sustainability=8, ai_disruption=5,
        automation=7, exit_potential=6,
    ),
    dict(
        id=19, name="Household CFO / personal budget kits", cat="B", family="Digital product",
        permission=1, permission_label="Consumer education; low conflict",
        capital=1, setup_time=4, weekly_time=3, time_to_income=5, income_potential=5,
        scalability=7, passivity=7, tech_difficulty=3, skill_fit=8, competition=8,
        bd_feasibility=8, intl_feasibility=7, reg_complexity=2, tax_complexity=3,
        employer_conflict=1, independence_risk=1, confidentiality_risk=1, reputation_risk=1,
        financial_risk=2, failure_prob=6, sustainability=7, ai_disruption=7,
        automation=8, exit_potential=5,
    ),
    dict(
        id=20, name="Notion / Sheets finance operating system", cat="B", family="Digital product",
        permission=1, permission_label="Generic productivity product",
        capital=1, setup_time=4, weekly_time=3, time_to_income=5, income_potential=5,
        scalability=7, passivity=7, tech_difficulty=3, skill_fit=7, competition=8,
        bd_feasibility=7, intl_feasibility=8, reg_complexity=2, tax_complexity=3,
        employer_conflict=1, independence_risk=1, confidentiality_risk=1, reputation_risk=1,
        financial_risk=2, failure_prob=6, sustainability=6, ai_disruption=7,
        automation=8, exit_potential=5,
    ),
    dict(
        id=21, name="Original professional-exam study assets", cat="B", family="Education",
        permission=2, permission_label="Must be original; no copyrighted institute material",
        capital=2, setup_time=7, weekly_time=4, time_to_income=6, income_potential=6,
        scalability=7, passivity=6, tech_difficulty=4, skill_fit=9, competition=8,
        bd_feasibility=8, intl_feasibility=6, reg_complexity=4, tax_complexity=3,
        employer_conflict=3, independence_risk=2, confidentiality_risk=2, reputation_risk=4,
        financial_risk=2, failure_prob=6, sustainability=6, ai_disruption=8,
        automation=6, exit_potential=5,
    ),
    dict(
        id=22, name="Generic accounting close checklists", cat="B", family="Digital product",
        permission=2, permission_label="Public-domain knowledge only; no firm methodology",
        capital=1, setup_time=4, weekly_time=2, time_to_income=5, income_potential=4,
        scalability=6, passivity=8, tech_difficulty=3, skill_fit=9, competition=7,
        bd_feasibility=7, intl_feasibility=7, reg_complexity=3, tax_complexity=3,
        employer_conflict=3, independence_risk=3, confidentiality_risk=4, reputation_risk=3,
        financial_risk=1, failure_prob=5, sustainability=6, ai_disruption=7,
        automation=8, exit_potential=4,
    ),
    dict(
        id=23, name="E-book: finance literacy for BD professionals", cat="B", family="Digital product",
        permission=2, permission_label="Education; no client stories; no Deloitte brand",
        capital=1, setup_time=6, weekly_time=2, time_to_income=6, income_potential=4,
        scalability=6, passivity=8, tech_difficulty=3, skill_fit=9, competition=7,
        bd_feasibility=8, intl_feasibility=5, reg_complexity=2, tax_complexity=3,
        employer_conflict=2, independence_risk=2, confidentiality_risk=2, reputation_risk=3,
        financial_risk=1, failure_prob=6, sustainability=6, ai_disruption=8,
        automation=7, exit_potential=4,
    ),
    dict(
        id=24, name="Paid newsletter (SME finance literacy)", cat="B", family="Content",
        permission=2, permission_label="Public education; not personalised advice",
        capital=1, setup_time=5, weekly_time=5, time_to_income=6, income_potential=5,
        scalability=6, passivity=5, tech_difficulty=3, skill_fit=9, competition=6,
        bd_feasibility=7, intl_feasibility=6, reg_complexity=3, tax_complexity=4,
        employer_conflict=3, independence_risk=3, confidentiality_risk=2, reputation_risk=4,
        financial_risk=1, failure_prob=6, sustainability=6, ai_disruption=7,
        automation=6, exit_potential=5,
    ),
    dict(
        id=25, name="Evergreen Excel course (Udemy + own site)", cat="B", family="Education",
        permission=3, permission_label="Teaching often needs written employer approval",
        capital=2, setup_time=8, weekly_time=4, time_to_income=7, income_potential=7,
        scalability=8, passivity=7, tech_difficulty=5, skill_fit=10, competition=8,
        bd_feasibility=8, intl_feasibility=8, reg_complexity=3, tax_complexity=4,
        employer_conflict=5, independence_risk=3, confidentiality_risk=2, reputation_risk=4,
        financial_risk=2, failure_prob=5, sustainability=8, ai_disruption=6,
        automation=7, exit_potential=6,
    ),
    dict(
        id=26, name="YouTube education library (Bangla + English)", cat="B", family="Content",
        permission=3, permission_label="Public content; brand/independence review advised",
        capital=2, setup_time=7, weekly_time=6, time_to_income=8, income_potential=6,
        scalability=8, passivity=5, tech_difficulty=5, skill_fit=9, competition=9,
        bd_feasibility=8, intl_feasibility=8, reg_complexity=3, tax_complexity=4,
        employer_conflict=4, independence_risk=3, confidentiality_risk=3, reputation_risk=6,
        financial_risk=2, failure_prob=7, sustainability=7, ai_disruption=6,
        automation=6, exit_potential=6,
    ),
    dict(
        id=27, name="SEO site: BD tax/VAT explainer (not advice)", cat="B", family="Content",
        permission=2, permission_label="Information publishing; strong disclaimer required",
        capital=2, setup_time=7, weekly_time=5, time_to_income=8, income_potential=6,
        scalability=7, passivity=6, tech_difficulty=5, skill_fit=9, competition=6,
        bd_feasibility=9, intl_feasibility=3, reg_complexity=5, tax_complexity=6,
        employer_conflict=4, independence_risk=4, confidentiality_risk=2, reputation_risk=6,
        financial_risk=2, failure_prob=6, sustainability=7, ai_disruption=7,
        automation=7, exit_potential=6,
    ),
    dict(
        id=28, name="LinkedIn authority + lead magnets", cat="C", family="Content",
        permission=3, permission_label="Personal brand; no firm/client disclosure",
        capital=1, setup_time=4, weekly_time=5, time_to_income=7, income_potential=5,
        scalability=6, passivity=4, tech_difficulty=3, skill_fit=9, competition=8,
        bd_feasibility=8, intl_feasibility=7, reg_complexity=3, tax_complexity=3,
        employer_conflict=4, independence_risk=3, confidentiality_risk=4, reputation_risk=6,
        financial_risk=1, failure_prob=5, sustainability=6, ai_disruption=6,
        automation=5, exit_potential=4,
    ),
    dict(
        id=29, name="Amazon KDP / long-form finance books", cat="B", family="Digital product",
        permission=2, permission_label="Original works; payouts/forex to be formalised",
        capital=1, setup_time=7, weekly_time=2, time_to_income=7, income_potential=4,
        scalability=6, passivity=8, tech_difficulty=3, skill_fit=8, competition=9,
        bd_feasibility=6, intl_feasibility=8, reg_complexity=4, tax_complexity=5,
        employer_conflict=2, independence_risk=2, confidentiality_risk=2, reputation_risk=3,
        financial_risk=1, failure_prob=7, sustainability=6, ai_disruption=8,
        automation=7, exit_potential=4,
    ),
    dict(
        id=30, name="Print-on-demand finance planners", cat="B", family="E-commerce",
        permission=1, permission_label="Generic consumer product",
        capital=2, setup_time=5, weekly_time=3, time_to_income=6, income_potential=4,
        scalability=6, passivity=7, tech_difficulty=3, skill_fit=6, competition=8,
        bd_feasibility=5, intl_feasibility=8, reg_complexity=3, tax_complexity=4,
        employer_conflict=1, independence_risk=1, confidentiality_risk=1, reputation_risk=1,
        financial_risk=2, failure_prob=7, sustainability=5, ai_disruption=5,
        automation=8, exit_potential=4,
    ),
    dict(
        id=31, name="Screened affiliate content (tools/books)", cat="B", family="Content",
        permission=3, permission_label="Avoid client software/relationships; disclose",
        capital=1, setup_time=4, weekly_time=4, time_to_income=6, income_potential=4,
        scalability=6, passivity=6, tech_difficulty=3, skill_fit=7, competition=8,
        bd_feasibility=6, intl_feasibility=7, reg_complexity=4, tax_complexity=4,
        employer_conflict=5, independence_risk=5, confidentiality_risk=2, reputation_risk=5,
        financial_risk=1, failure_prob=7, sustainability=4, ai_disruption=6,
        automation=7, exit_potential=3,
    ),
    dict(
        id=32, name="AI prompt packs for accountants", cat="B", family="AI / tech",
        permission=2, permission_label="Generic prompts; no client/firm data examples",
        capital=1, setup_time=4, weekly_time=3, time_to_income=4, income_potential=4,
        scalability=6, passivity=7, tech_difficulty=3, skill_fit=8, competition=9,
        bd_feasibility=7, intl_feasibility=8, reg_complexity=2, tax_complexity=3,
        employer_conflict=2, independence_risk=2, confidentiality_risk=3, reputation_risk=3,
        financial_risk=1, failure_prob=7, sustainability=3, ai_disruption=9,
        automation=8, exit_potential=3,
    ),
    dict(
        id=33, name="AI BD tax/VAT calculator microsite", cat="B", family="AI / tech",
        permission=2, permission_label="Calculator + disclaimer; not a tax practice",
        capital=3, setup_time=7, weekly_time=4, time_to_income=6, income_potential=6,
        scalability=8, passivity=7, tech_difficulty=7, skill_fit=9, competition=5,
        bd_feasibility=9, intl_feasibility=2, reg_complexity=6, tax_complexity=7,
        employer_conflict=4, independence_risk=4, confidentiality_risk=2, reputation_risk=6,
        financial_risk=3, failure_prob=6, sustainability=7, ai_disruption=5,
        automation=9, exit_potential=7,
    ),
    dict(
        id=34, name="Micro-SaaS: invoice + Mushak helper", cat="B", family="AI / tech",
        permission=3, permission_label="Software product; may become a business to declare",
        capital=4, setup_time=9, weekly_time=6, time_to_income=8, income_potential=8,
        scalability=9, passivity=6, tech_difficulty=8, skill_fit=8, competition=6,
        bd_feasibility=8, intl_feasibility=2, reg_complexity=7, tax_complexity=6,
        employer_conflict=5, independence_risk=5, confidentiality_risk=4, reputation_risk=5,
        financial_risk=5, failure_prob=7, sustainability=8, ai_disruption=5,
        automation=9, exit_potential=8,
    ),
    dict(
        id=35, name="Automated BD macro/indicator portal", cat="B", family="AI / tech",
        permission=2, permission_label="Public data republishing; cite sources",
        capital=3, setup_time=7, weekly_time=3, time_to_income=8, income_potential=5,
        scalability=7, passivity=8, tech_difficulty=7, skill_fit=8, competition=4,
        bd_feasibility=8, intl_feasibility=5, reg_complexity=3, tax_complexity=3,
        employer_conflict=2, independence_risk=2, confidentiality_risk=1, reputation_risk=2,
        financial_risk=3, failure_prob=6, sustainability=7, ai_disruption=4,
        automation=9, exit_potential=6,
    ),
    dict(
        id=36, name="Productized Excel model review (foreign, non-restricted)", cat="C", family="Leveraged service",
        permission=4, permission_label="Outside professional service — written approval required",
        capital=1, setup_time=4, weekly_time=6, time_to_income=4, income_potential=6,
        scalability=5, passivity=3, tech_difficulty=5, skill_fit=10, competition=6,
        bd_feasibility=5, intl_feasibility=8, reg_complexity=5, tax_complexity=5,
        employer_conflict=8, independence_risk=8, confidentiality_risk=6, reputation_risk=6,
        financial_risk=2, failure_prob=4, sustainability=5, ai_disruption=7,
        automation=4, exit_potential=3,
    ),
    dict(
        id=37, name="Weekend public Excel workshops", cat="C", family="Education",
        permission=3, permission_label="Teaching / outside activity — approval likely required",
        capital=2, setup_time=5, weekly_time=5, time_to_income=4, income_potential=5,
        scalability=4, passivity=2, tech_difficulty=4, skill_fit=10, competition=5,
        bd_feasibility=8, intl_feasibility=3, reg_complexity=3, tax_complexity=4,
        employer_conflict=6, independence_risk=3, confidentiality_risk=2, reputation_risk=4,
        financial_risk=2, failure_prob=4, sustainability=5, ai_disruption=6,
        automation=3, exit_potential=2,
    ),
    dict(
        id=38, name="Recorded corporate training for non-restricted entities", cat="C", family="Education",
        permission=4, permission_label="High conflict; written approval mandatory",
        capital=2, setup_time=6, weekly_time=4, time_to_income=5, income_potential=7,
        scalability=6, passivity=5, tech_difficulty=4, skill_fit=10, competition=5,
        bd_feasibility=7, intl_feasibility=5, reg_complexity=5, tax_complexity=5,
        employer_conflict=9, independence_risk=8, confidentiality_risk=5, reputation_risk=7,
        financial_risk=2, failure_prob=4, sustainability=6, ai_disruption=5,
        automation=6, exit_potential=4,
    ),
    dict(
        id=39, name="Student mentorship (low-touch, non-client)", cat="C", family="Education",
        permission=3, permission_label="Usually low risk if unpaid/low-paid and non-client",
        capital=1, setup_time=3, weekly_time=4, time_to_income=5, income_potential=3,
        scalability=3, passivity=2, tech_difficulty=2, skill_fit=8, competition=4,
        bd_feasibility=8, intl_feasibility=4, reg_complexity=2, tax_complexity=2,
        employer_conflict=3, independence_risk=2, confidentiality_risk=2, reputation_risk=2,
        financial_risk=1, failure_prob=3, sustainability=5, ai_disruption=4,
        automation=2, exit_potential=1,
    ),
    dict(
        id=40, name="Upwork financial modelling / accounting", cat="C", family="Freelance",
        permission=4, permission_label="Outside professional employment — approval required",
        capital=1, setup_time=3, weekly_time=8, time_to_income=3, income_potential=6,
        scalability=3, passivity=2, tech_difficulty=5, skill_fit=10, competition=8,
        bd_feasibility=7, intl_feasibility=8, reg_complexity=5, tax_complexity=5,
        employer_conflict=9, independence_risk=9, confidentiality_risk=7, reputation_risk=7,
        financial_risk=2, failure_prob=4, sustainability=4, ai_disruption=8,
        automation=3, exit_potential=2,
    ),
    dict(
        id=41, name="Fiverr bookkeeping / tax-form gigs", cat="C", family="Freelance",
        permission=5, permission_label="High conflict + quality/reputation risk — avoid",
        capital=1, setup_time=3, weekly_time=8, time_to_income=3, income_potential=4,
        scalability=2, passivity=1, tech_difficulty=4, skill_fit=8, competition=9,
        bd_feasibility=6, intl_feasibility=7, reg_complexity=6, tax_complexity=6,
        employer_conflict=9, independence_risk=9, confidentiality_risk=8, reputation_risk=8,
        financial_risk=2, failure_prob=5, sustainability=3, ai_disruption=9,
        automation=3, exit_potential=1,
    ),
    dict(
        id=42, name="Direct SME accounting retainer (BD)", cat="C", family="Professional service",
        permission=5, permission_label="Core conflict with firm/clients — do not pursue",
        capital=2, setup_time=5, weekly_time=8, time_to_income=4, income_potential=7,
        scalability=3, passivity=1, tech_difficulty=5, skill_fit=10, competition=6,
        bd_feasibility=8, intl_feasibility=2, reg_complexity=7, tax_complexity=7,
        employer_conflict=10, independence_risk=10, confidentiality_risk=8, reputation_risk=9,
        financial_risk=3, failure_prob=4, sustainability=4, ai_disruption=6,
        automation=3, exit_potential=3,
    ),
    dict(
        id=43, name="Digital marketing / content agency", cat="C", family="Business",
        permission=4, permission_label="Business ownership + time conflict",
        capital=4, setup_time=8, weekly_time=9, time_to_income=5, income_potential=7,
        scalability=6, passivity=2, tech_difficulty=6, skill_fit=4, competition=8,
        bd_feasibility=7, intl_feasibility=7, reg_complexity=5, tax_complexity=5,
        employer_conflict=7, independence_risk=5, confidentiality_risk=3, reputation_risk=5,
        financial_risk=5, failure_prob=7, sustainability=5, ai_disruption=7,
        automation=5, exit_potential=6,
    ),
    dict(
        id=44, name="Residential rental property (Dhaka/CTG)", cat="A", family="Real assets",
        permission=2, permission_label="Personal investment; tenant/entity screening",
        capital=10, setup_time=8, weekly_time=4, time_to_income=6, income_potential=6,
        scalability=4, passivity=5, tech_difficulty=3, skill_fit=6, competition=5,
        bd_feasibility=7, intl_feasibility=1, reg_complexity=6, tax_complexity=6,
        employer_conflict=2, independence_risk=3, confidentiality_risk=1, reputation_risk=2,
        financial_risk=8, failure_prob=4, sustainability=8, ai_disruption=1,
        automation=3, exit_potential=7,
    ),
    dict(
        id=45, name="Content-site / domain portfolio flipping", cat="B", family="Digital asset",
        permission=2, permission_label="Generic publishing; no restricted-entity sites",
        capital=3, setup_time=6, weekly_time=4, time_to_income=8, income_potential=5,
        scalability=6, passivity=6, tech_difficulty=5, skill_fit=5, competition=7,
        bd_feasibility=6, intl_feasibility=8, reg_complexity=3, tax_complexity=4,
        employer_conflict=2, independence_risk=2, confidentiality_risk=1, reputation_risk=3,
        financial_risk=4, failure_prob=7, sustainability=5, ai_disruption=7,
        automation=7, exit_potential=8,
    ),
]


def composite(o: dict) -> float:
    score = 0.0
    for k, w in WEIGHTS.items():
        raw = o[k]
        if k in POSITIVE:
            score += w * (raw / 10.0) * 100
        else:
            score += w * ((11 - raw) / 10.0) * 100
    return round(score, 1)


for _o in OPPS:
    _o["score"] = composite(_o)


def ranked():
    return sorted(OPPS, key=lambda x: x["score"], reverse=True)


# --- Financial scenario assumptions (labelled estimates, not forecasts) ---
SCENARIOS = {
    "conservative": {
        "label": "Conservative",
        "initial_capital_bdt": 150_000,
        "monthly_contrib_bdt": 15_000,
        "hours_week": "5–7",
        "income_m6": (3_000, 8_000),
        "income_m12": (8_000, 18_000),
        "income_m24": (15_000, 35_000),
        "income_m36": (22_000, 50_000),
        "annual_y3": (280_000, 650_000),
        "blend_yield": "8–11% on invested sleeve (govt securities / DPS)",
    },
    "balanced": {
        "label": "Balanced",
        "initial_capital_bdt": 400_000,
        "monthly_contrib_bdt": 30_000,
        "hours_week": "7–10",
        "income_m6": (6_000, 18_000),
        "income_m12": (18_000, 45_000),
        "income_m24": (35_000, 90_000),
        "income_m36": (50_000, 130_000),
        "annual_y3": (650_000, 1_700_000),
        "blend_yield": "9–12% invested sleeve + growing digital royalties",
    },
    "aggressive": {
        "label": "Aggressive-but-reasonable",
        "initial_capital_bdt": 1_000_000,
        "monthly_contrib_bdt": 50_000,
        "hours_week": "10–14 (protect audit peak seasons)",
        "income_m6": (10_000, 30_000),
        "income_m12": (30_000, 80_000),
        "income_m24": (70_000, 180_000),
        "income_m36": (100_000, 280_000),
        "annual_y3": (1_300_000, 3_400_000),
        "blend_yield": "Invested sleeve + scaled product catalogue; still no leverage/speculation",
    },
}

PORTFOLIOS = {
    "career_first": {
        "name": "Career-First Capital Preserver",
        "alloc": [
            ("Sovereign & bank deposits (T-bill/T-bond/NSC/FDR/DPS)", 70),
            ("Screened open-end mutual funds", 10),
            ("Digital product studio (templates)", 15),
            ("Experimental calculators / content tests", 5),
        ],
    },
    "builder": {
        "name": "Balanced Builder",
        "alloc": [
            ("Sovereign & bank deposits", 50),
            ("Screened funds / limited cleared equity", 15),
            ("Digital products + evergreen course", 25),
            ("AI microsite / experimental", 10),
        ],
    },
    "asset": {
        "name": "Asset-Compounder (Year 2–3 tilt)",
        "alloc": [
            ("Sovereign ladder + DPS", 45),
            ("Screened long-term funds", 15),
            ("Productised knowledge assets", 30),
            ("Optional rental reserve (only if surplus + approval path)", 10),
        ],
    },
}
